# Site settings
title: Noah Manger
email: noah.manger@gmail.com
description: Personal site of Noah Manger. Work in progress.
baseurl: "http://noahmanger.me"
url: "http://noahmanger.com" # the base hostname & protocol for your site
twitter_username: noahmanger
github_username:  noahmanger
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

